### PR TITLE
Argon2 v10 fix

### LINKED ISSUE #54: Argon2 v1.0 hashes might not include "v=16" parameter
This kind of falls in the list of #11 , but is a bit more important.

Apparently the older version of Argon2 didn't always enforce the `$v=16$` version parameter in the hash, so we should also accept hashes that do not include the version parameter and default it to `Version10`.

The change would basically only include `Data.Password.Argon2.checkPassword`.

### PR DESCRIPTION
**Pull request by Vlix**
Aims to fix #54 

Argon2 hash without a version part will be interpreted as having been hashed with version 1.0 (`v=16`)

Not so much a "bug", especially since almost all usages of Argon2 are generally version 1.3, but it's a small effort to also accept hashes without a version part.

### CODE REVIEW

**Comment by Vlix** [comment]
Just remembered it might be a good idea to also mention this in the documentation of `Argon2`? Or is that unnecessary? :thinking:

**Comment by cdepillabout** [comment]
Sorry for taking a long time to respond to this.  I hope to get to this in a few days.

**Comment by Vlix** [comment]
No rush, this isn't a pressing fix 👌

File: password/src/Data/Password/Argon2.hs [hunk 1]
```diff
@@ -277,30 +277,40 @@ checkPassword :: Password -> PasswordHash Argon2 -> PasswordCheck
...
+        _ -> Nothing
   where
-    argon2Salt = 16 -- only here because of warnings
     parseVariant = splitMaybe "argon2" letterToVariant
     parseVersion = splitMaybe "v=" numToVersion
-    parseParameters params = do
-        let ps = T.split (== ',') params
-        guard $ Prelude.length ps == 3
-        go ps (Nothing, Nothing, Nothing)
+    parseAll argon2Variant argon2Version parametersT salt64 hashedKey64 = do
```
Comment (cdepillabout) [inline password/src/Data/Password/Argon2.hs:303]: Just a nitpick, but I felt like I wanted a type signature on this function.  I thought it might be a little easier to see exactly what it is doing.

**Review by cdepillabout — APPROVED** [review]
This LGTM!

File: password/src/Data/Password/Argon2.hs (hunk 1 above)
Comment (Vlix) [reply password/src/Data/Password/Argon2.hs:303]:
```hs
parseAll :: Argon2.Variant -> Argon2.Version -> Text -> Text -> Text -> Maybe (Argon2Params, Salt Argon2, ByteString)
```
Sure, I'll add this in before I merge it.
